/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadgrupo6.vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import universidadgrupo6.AccesoADatos.AlumnoData;
import universidadgrupo6.AccesoADatos.InscripcionData;
import universidadgrupo6.Entidades.Alumno;
import universidadgrupo6.Entidades.Inscripcion;
import universidadgrupo6.Entidades.Materia;

/**
 *
 * @author Hernan
 */
public class InscripcionesView extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private int idAlumno;

    /**
     * Creates new form InscripcionesView
     */
    public InscripcionesView() {
        initComponents();
        armarCabecera();
        llenarComboBox();

        //llenarTablaNoCursadas();
        // llenarTablaCursadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        comboBoxAlumno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jrMateCur = new javax.swing.JRadioButton();
        jrMateNo = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbAnularInscripcion = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        comboBoxAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione alumno");

        jLabel2.setText("Listados de Materias");

        buttonGroup1.add(jrMateCur);
        jrMateCur.setText("Materias cursadas");
        jrMateCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateCurActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrMateNo);
        jrMateNo.setText("Materias No cursadas");
        jrMateNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrMateNoActionPerformed(evt);
            }
        });

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(jtMaterias);

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbAnularInscripcion.setText("Anular inscripción");
        jbAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularInscripcionActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1)
                        .addGap(66, 66, 66)
                        .addComponent(comboBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbInscribir)
                                .addGap(187, 187, 187)
                                .addComponent(jbAnularInscripcion)
                                .addGap(232, 232, 232)
                                .addComponent(jbSalir))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jrMateCur)
                                    .addGap(48, 48, 48)
                                    .addComponent(jrMateNo))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrMateCur)
                    .addComponent(jrMateNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbAnularInscripcion)
                    .addComponent(jbSalir))
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxAlumnoActionPerformed
        Alumno alu = (Alumno) comboBoxAlumno.getSelectedItem();
        idAlumno = alu.getIdAlumno();
        if (jtMaterias.getRowCount() > 0) {
            limpiarTabla();
        }


    }//GEN-LAST:event_comboBoxAlumnoActionPerformed

    private void jrMateNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateNoActionPerformed
        limpiarTabla();
        llenarTablaNoCursadas();
        jbInscribir.setEnabled(true);
        jbAnularInscripcion.setEnabled(false);


    }//GEN-LAST:event_jrMateNoActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        InscripcionData insdat = new InscripcionData();
        int filas = jtMaterias.getSelectedRow();
        int idMateria = (Integer) jtMaterias.getValueAt(filas, 0);
        Inscripcion incr = new Inscripcion(idAlumno, idMateria);
        insdat.guardarInscripcion(incr);
        limpiarTabla();
        llenarTablaNoCursadas();
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jrMateCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrMateCurActionPerformed

        limpiarTabla();
        llenarTablaCursadas();
        jbInscribir.setEnabled(false);
        jbAnularInscripcion.setEnabled(true);


    }//GEN-LAST:event_jrMateCurActionPerformed

    private void jbAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularInscripcionActionPerformed

        InscripcionData insdat = new InscripcionData();
        int filas = jtMaterias.getSelectedRow();
        int idMateria = (Integer) jtMaterias.getValueAt(filas, 0);
        insdat.BorrarInscripcion(idMateria, idAlumno);
        limpiarTabla();
        llenarTablaCursadas();
    }//GEN-LAST:event_jbAnularInscripcionActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();

    }//GEN-LAST:event_jbSalirActionPerformed
    public void llenarComboBox() {
        ArrayList<Alumno> alumnos = new ArrayList<>();
        AlumnoData ad = new AlumnoData();
        alumnos = ad.listarAlumno();
        for (Alumno alumno : alumnos) {
            comboBoxAlumno.addItem(alumno);
        }
    }

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
        jtMaterias.setModel(modelo);
    }

    private void llenarTablaCursadas() {
        ArrayList<Materia> materiaCursadas = new ArrayList<>();
        // int sumador=0;
        InscripcionData id = new InscripcionData();
        materiaCursadas = id.ListarMateriasCursadas(idAlumno);
        for (Materia materia : materiaCursadas) {
            cargarDatos(materia);
        }
    }

    private void llenarTablaNoCursadas() {
        ArrayList<Materia> materiaNoCursadas = new ArrayList<>();
        // int sumador=0;
        InscripcionData id = new InscripcionData();
        materiaNoCursadas = id.ListarMateriasNOCursadas(idAlumno);
        for (Materia materia : materiaNoCursadas) {
            cargarDatos(materia);
        }
    }

    private void cargarDatos(Materia materia) {
        modelo.addRow(new Object[]{materia.getIdMateria(), materia.getNombre(), materia.getAnio()});
    }

    private void limpiarTabla() {
        for (int i = 0; i < jtMaterias.getRowCount(); i++) {
            modelo.removeRow(i);
            i -= 1;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<Alumno> comboBoxAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularInscripcion;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JButton jbSalir;
    private javax.swing.JRadioButton jrMateCur;
    private javax.swing.JRadioButton jrMateNo;
    private javax.swing.JTable jtMaterias;
    // End of variables declaration//GEN-END:variables

}
